name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 'macOS', os: 'macos-latest'}
          - {name: 'macOS Ventura', os: 'macos-13'}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test make uninstall-homebrew
        run: make uninstall-homebrew
      - name: Test make install
        run: make install
      - name: Test make update
        run: |
          make update
          cat Brewfile
      - name: Test make uninstall
        run: make uninstall
